accounts/urls.py
from django.urls import path
from django.conf.urls import url
from accounts import views
from django.shortcuts import redirect



app_name = 'accounts'

urlpatterns = [
    path('', views.login_view,name='login_view'),
    path('signup/', views.signup_view,name='signup_view'),
    path('homepage/', views.homepage_view,name='homepage_view'),
    path('logout/',views.logout_view,name='logout'),
    path('changepassword/',views.change_password_view,name='changepassword'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('<username>/', views.profile_view, name="profile"),

    # path('', lambda req: redirect('homepage/')),
]

login-system/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class UserProfileInfo(models.Model):
#     user = models.OneToOneField(User)
#     profile_pic = models.ImageField(upload_to='profile_pics')

#     def __str__(self):
#         return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages

# from accounts import UserProfileInfo

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)#hides password on input
    
    class Meta():
        model=User
        fields = ['username', 'password']
        # fields = "__all__"
    

    def clean(self,*args,**kwargs):
        username=self.cleaned_data.get("username")
        password=self.cleaned_data.get("password")
        user_qs = User.objects.filter(username=username)
        if user_qs.count() == 0:
            raise forms.ValidationError("username does not exist")
        else:
            if username is not None and password:
                user = authenticate(username=username, password=password)
                # print(user)
                #if not user.is_active:
                if user is None:
                    raise forms.ValidationError("Account is not activated.")
                    # messages.error(self,'Account is not activated.')
                if not user:
                    raise forms.ValidationError("Incorrect password")
                

        return super(LoginForm,self).clean(*args,**kwargs)


class RegistrationForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)#hides password on input
    repassword = forms.CharField(widget=forms.PasswordInput)
   
    class Meta():
        model=User
        fields = ['username','email', 'password', 'repassword']

    def clean(self):
        """
        Verifies that the values entered into the password fields match

        NOTE: Errors here will appear in ``non_field_errors()`` because it applies to more than one field.
        """
        cleaned_data = super(RegistrationForm, self).clean()
        if 'password' in self.cleaned_data and 'repassword' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['repassword']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return self.cleaned_data
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.exclude(pk=self.instance.pk).filter(username=username).exists():
            raise forms.ValidationError(u'Username "%s" is already in use.' % username)
        return username

    def save(self, commit=True):
        users = super(RegistrationForm, self).save(commit=False)
        users.set_password(self.cleaned_data['password'])

        if commit:
            users.save()
        return users

accounts/views.py
from django.shortcuts import render, redirect

from accounts import forms

from django.http import HttpResponseRedirect,HttpResponse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.forms import PasswordChangeForm   

from django.urls import reverse

from django.core.mail import EmailMessage, EmailMultiAlternatives

from django.template.loader import render_to_string

from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.safestring import mark_safe


# Create your views here.


# Signup View
def signup_view(request):
    if request.method == "GET":
        username = request.GET.get('username')
        # print(username)
        if username is not None:
            if User.objects.filter(username__iexact=username):
                return HttpResponse(False)
            else:
                return HttpResponse(True)

    if request.method == 'POST':
        
        form = forms.RegistrationForm(data=request.POST)
        if form.is_valid():
            users = form.save(commit=False)
            users.is_active = False
            users.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('accounts/acc_activate_email.html', {
                'user': users,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(users.pk)),
                'token': default_token_generator.make_token(users),
            })
            to_email = form.cleaned_data.get('email')
            msg = EmailMultiAlternatives(mail_subject, message, 'ihave10.0gpa@gmail.com', to=[to_email])
            msg.attach_alternative(message, "text/html")
            msg.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = forms.RegistrationForm()
    return render(request,'accounts/signup.html', {'form': form,})




# Email Activation Function
def activate(request, uidb64, token):

    UserModel = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Email Activation Successful')
        return redirect('accounts:login_view')
    else:
        return HttpResponse('Activation link is invalid!')


# Login View
def login_view(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user=authenticate(username=request.POST['username'],password=request.POST['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("accounts:homepage_view")
            else:
                return HttpResponse("You not are active but logged in!...")
    else:
        form=forms.LoginForm()
    return render(request,'accounts/login.html', {'form': form,})    



# HomePage View
@login_required(login_url='/')
def homepage_view(request):
    return render(request,'accounts/homepage.html')



@login_required(login_url='/')
def logout_view(request):
    logout(request)      
    return HttpResponseRedirect('/')


@login_required(login_url='/')
def change_password_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponse('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })


def profile_view(request,username=None):
    try:
        user = User.objects.get(username=username)
        if(user is not None):
            return render(request, "accounts/profile.html", {"user": user,})
        else:
            return render("User not found")
    except User.DoesNotExist:
        return HttpResponse("User not found")

accounts/templates/accounts/acc_activate_email.html
{% autoescape off %}  
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <div class="jumbotron jumbotron-fluid">
    <h1>Verify your email to finish signing up with Us!</h1>
  </div>
  <div class="row">
    <div class="col-sm-8">
        <h3>Hey {{ user.username }},</h3>  
        <p>Please confirm that <b color='black'>{{ user.email }}</b> is your email address and click on the below link to confirm your email,
            http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}<br><br>  </p>
            <h3>If you think, it's not you, then just ignore this email.</h3>  
    </div>
    </div>    
</div>
</body>
</html>
{% endautoescape %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

  <div class="bs-example">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      {% if user.is_authenticated %}
      <a href="{% url 'accounts:homepage_view' %}" class="navbar-brand">Login-System</a>  
      {% else %}
      <a href="{% url 'accounts:login_view' %}" class="navbar-brand">Login-System</a>
      {% endif %}
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          {% if user.is_authenticated %}  
          <div class="navbar-nav">
                <a href="#" class="nav-item nav-link active">Home</a>
                <a href="{% url 'accounts:profile' user.username %}" class="nav-item nav-link">Profile</a>
                <a href="#" class="nav-item nav-link">Messages</a>
                <a href="#" class="nav-item nav-link disabled" tabindex="-1">Reports</a>
            </div>
            {% endif %}
            
            <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <a href="{% url 'accounts:logout' %}" class="nav-item nav-link active">Logout</a>
            {% else %}
              <a href="{% url 'accounts:login_view' %}" class="nav-item nav-link ac tive">Login</a>
              <a href="{% url 'accounts:signup_view' %}" class="nav-item nav-link active">Signup</a>
            </div>
            {% endif %}

        </div>
    </nav>
</div>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="{% static 'accounts/js/main.js' %}" type="text/javascript"></script>


  <!-- <div class="jumbotron text-center">
  <h1>My First Bootstrap Page</h1>
  <p>Resize this responsive page to see the effect!</p> 
</div> -->

    {%block body_block%}

    {%endblock%}

</body>

</html>

accounts/templates/accounts/change_password.html
{% extends "accounts/base.html" %}
{% block body_block %}


<div class="container">

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save changes</button>

{% endblock %}

accounts/templates/accounts/homepage.html
{% extends "accounts/base.html" %}
{% block body_block %}



<div class="container" style='margin-top:40px;'>
    <h1>Blockquotes</h1>
    <p>The blockquote element is used to present content from another source:</p>
    <blockquote class="blockquote">
      <p>For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
      <footer class="blockquote-footer">From WWF's website</footer>
    </blockquote>
  </div>


  {% endblock %}  

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block body_block %}

<div class="jumbotron text-center">
  <h1>My First Bootstrap Page</h1>
  <p>Resize this responsive page to see the effect!</p>
</div>


<div class="container">

  <form method="POST">
    {% csrf_token %}


    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success">
      <a class="close" href="#" data-dismiss="alert">×</a>
      {{ message }}
    </div>
    {% endif %}
    {% endfor %}

    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert alert-danger">
      <a class="close" href="#" data-dismiss="alert">×</a>
      {{ message }}
    </div>
    {% endif %}
    {% endfor %}


    <div class="form-group">
      <label for="{{ form.name.id_for_label }}">Username:</label>
      <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
      <div class="valid-feedback">Valid.</div>
      {% if form.errors %}
      {% for error in form.username.errors %}
      <p style="color: red;"> {{ error }} </p>
      {% endfor %}
      {% endif %}
    </div>

    <div class="form-group">
      <label for="{{ form.password.id_for_label }}">Password:</label>
      <input type="password" class="form-control" id="password" placeholder="Enter password" name="password">
      <div class="valid-feedback">Valid.</div>
      {% if form.errors %}
      {% for error in form.password.errors %}
      <p style="color: red;"> {{ error }} </p>
      {% endfor %}
      {% endif %}
    </div>

    {% for error in form.non_field_errors %}
    <p style="color: red;"> {{ error }} </p>
    {% endfor %}

    <input type='submit' class='btn btn-primary'  value='submit'>
  
  </form>
</div>
{% endblock %}  

accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}
{% block body_block %}

<div class="container">
<p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>



</div>


{% endblock %}  

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% block body_block %}



<div class="container">

<form method="POST">
    <!-- <p style="color: red;">{{ form.non_field_errors }}</p> -->

    {% csrf_token %}
    <div class="form-group" style='margin-top:40px;'>
        <label for="{{ form.name.id_for_label }}">Username:</label>
        <input type="text" class="form-control" id="username" placeholder="Enter username" name="username" required>
        <p id="availabality"></p>
        {% if form.errors %}
            {% for error in form.username.errors %}
                <p style="color: red;"> {{ error }} </p>
            {% endfor %}
        {% endif %}
    </div>

    <div class="form-group">
        <label for="{{ form.email.id_for_label }}">Email:</label>
        <input type="text" class="form-control" id="email" placeholder="Enter email" name="email" required>
        {% if form.errors %}
            {% for error in form.email.errors %}
                <p style="color: red;"> {{ error }} </p>
            {% endfor %}
        {% endif %}
    </div>
    
     <div class="form-group">
        <label for="{{ form.password.id_for_label }}">Password:</label>
        <input type="password" class="form-control" id="password" placeholder="Enter password" name="password" required>
        <div class="valid-feedback">Valid.</div>      
        {% if form.errors %}
            {% for error in form.password.errors %}
                <p style="color: red;"> {{ error }} </p>
            {% endfor %}
        {% endif %}       
    </div>

    <div class="form-group">
        <label for="{{ form.repassword.id_for_label }}">Retype Password:</label>
        <input type="password" class="form-control" id="repassword" placeholder="Enter password" name="repassword" required>
        <div class="valid-feedback">Valid.</div>      
        {% if form.errors %}
            {% for error in form.repassword.errors %}
                <p style="color: red;"> {{ error }} </p>
            {% endfor %}
        {% endif %}  
    </div>
    



      <div class="form-group form-check">
        <label class="form-check-label">
          <input class="form-check-input" type="checkbox" name="remember" required> I agree to terms and conditions.
          <div class="valid-feedback">Valid.</div>
          <div class="invalid-feedback">Check this checkbox to continue.</div>
        </label>
      </div>


      {% for error in form.non_field_errors %}
            <p style="color: red;"> {{ error }} </p>
      {% endfor %}
      <input type='submit' class='btn btn-primary' value='submit'>
    </form>
</div>


{% endblock %}

accounts/templates/accounts/temp.html
    {% csrf_token %}
    
    <div class="form-group">
       <label for="{{ form.password.id_for_label }}">Password:</label>
       <input type="password" class="form-control" id="password" placeholder="Enter password" name="password" required>
       <div class="valid-feedback">Valid.</div>      
       {% if form.errors %}
           {% for error in form.password.errors %}
               <p style="color: red;"> {{ error }} </p>
           {% endfor %}
       {% endif %}       
   </div>

   <div class="form-group">
       <label for="{{ form.repassword.id_for_label }}">Retype Password:</label>
       <input type="password" class="form-control" id="repassword" placeholder="Enter password" name="repassword" required>
       <div class="valid-feedback">Valid.</div>      
       {% if form.errors %}
           {% for error in form.repassword.errors %}
               <p style="color: red;"> {{ error }} </p>
           {% endfor %}
       {% endif %}  
   </div>

     {% for error in form.non_field_errors %}
           <p style="color: red;"> {{ error }} </p>
     {% endfor %}
     <input type='submit' class='btn btn-primary' value='submit'>
   </form>
</div>